BEGIN TRANSACTION;
CREATE TABLE "Users" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`chatID`	TEXT,
	`isAdmin`	INTEGER NOT NULL
);
CREATE TABLE "Track" (
	`TrackID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`ItemID`	INTEGER,
	`UserID`	INTEGER,
	`TargetAmount`	INTEGER,
	FOREIGN KEY(`ItemID`) REFERENCES `Items`(`id`),
	FOREIGN KEY(`UserID`) REFERENCES `Users`(`id`)
);
CREATE TABLE "Prices" (
	`PricesID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`ItemID`	INTEGER,
	`Condition`	INTEGER,
	`Amount`	INTEGER,
	`CreatedAt`	TIMESTAMP,
	`CurrencyCode`	TEXT,
	FOREIGN KEY(`ItemID`) REFERENCES `Items`(`id`)
);
CREATE TABLE "Items" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`asin`	TEXT,
	`url`	TEXT
);
COMMIT;
